"""sync DB state after manual index creation

Revision ID: 794dbcf91a85
Revises: 5f1db463f8c6
Create Date: 2026-02-15 16:57:29.562336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '794dbcf91a85'
down_revision: Union[str, None] = '5f1db463f8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimate_events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('estimate_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When event was successfully processed to Drive',
               existing_nullable=True)
    op.alter_column('estimate_events', 'retry_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of processing retry attempts',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('estimate_events', 'error',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Last error message if processing failed',
               existing_nullable=True)
    op.drop_index('ix_estimate_event_processed_at', table_name='estimate_events')
    op.drop_index('ix_estimate_event_unprocessed', table_name='estimate_events', postgresql_where='(processed_at IS NULL)')
    op.drop_index('ix_estimate_events_unprocessed', table_name='estimate_events')
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events')
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('ix_estimates_is_deleted'), 'estimates', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimates_is_deleted'), table_name='estimates')
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_estimate_events_unprocessed', 'estimate_events', ['processed_at'], unique=False)
    op.create_index('ix_estimate_event_unprocessed', 'estimate_events', ['processed_at', 'retry_count'], unique=False, postgresql_where='(processed_at IS NULL)')
    op.create_index('ix_estimate_event_processed_at', 'estimate_events', [sa.text('processed_at DESC')], unique=False)
    op.alter_column('estimate_events', 'error',
               existing_type=sa.VARCHAR(length=500),
               comment='Last error message if processing failed',
               existing_nullable=True)
    op.alter_column('estimate_events', 'retry_count',
               existing_type=sa.INTEGER(),
               comment='Number of processing retry attempts',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('estimate_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When event was successfully processed to Drive',
               existing_nullable=True)
    op.alter_column('estimate_events', 'event_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
