"""remove_direction

Revision ID: bb6ea7cfdff3
Revises: e819ef15b17e
Create Date: 2026-04-15 14:05:54.025741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6ea7cfdff3'
down_revision: Union[str, None] = 'e819ef15b17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events')
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
