"""Increase ticker symbol length to 20

Revision ID: c5e1735a6f83
Revises: a3b5c7d9e1f0
Create Date: 2026-03-28 18:21:30.306116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e1735a6f83'
down_revision: Union[str, None] = 'a3b5c7d9e1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimate_event_timeline'), table_name='estimate_events')
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.alter_column('tickers', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('ix_estimate_event_timeline'), 'estimate_events', ['estimate_id', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
