"""Add realized pnl percent

Revision ID: cbe54226e72d
Revises: c5e1735a6f83
Create Date: 2026-04-12 13:26:15.638939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe54226e72d'
down_revision: Union[str, None] = 'c5e1735a6f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events')
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.add_column('estimates', sa.Column('realized_pnl_percent', sa.DECIMAL(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'realized_pnl_percent')
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
