"""add_ai_version

Revision ID: e819ef15b17e
Revises: cbe54226e72d
Create Date: 2026-04-15 12:47:14.481800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e819ef15b17e'
down_revision: Union[str, None] = 'cbe54226e72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events')
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.add_column('estimates', sa.Column('ai_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'ai_version')
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
