"""Initial models: Ticker, Estimate, EstimateEvent, MarketData, User, Role

Revision ID: f9f513c6220d
Revises: 
Create Date: 2026-02-07 19:06:10.631075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9f513c6220d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'USER', 'READONLY', name='role_type'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('INITIAL_IMPORT', 'DAILY_HISTORY_UPDATE', 'ON_ESTIMATE_SAVE', 'MANUAL_SYNC', name='sync_job_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='sync_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('checksum_before', sa.String(length=64), nullable=True),
    sa.Column('checksum_after', sa.String(length=64), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_jobs_started_at', 'sync_jobs', ['started_at'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('stock', 'etf', 'crypto')", name='ck_ticker_asset_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticker_symbol', 'tickers', ['symbol'], unique=False)
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('start_price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('target_price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('stop_loss_price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('target_profit_percent', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('stop_loss_percent', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED_WIN', 'CLOSED_LOSS', 'CLOSED_MANUAL', 'EXPIRED', name='estimate_status'), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='direction'), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 100)', name='ck_estimate_ai_confidence_range'),
    sa.CheckConstraint('start_price > 0', name='ck_estimate_start_price_positive'),
    sa.CheckConstraint('stop_loss_price > 0', name='ck_estimate_stop_loss_price_positive'),
    sa.CheckConstraint('target_price > 0', name='ck_estimate_target_price_positive'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estimate_created_at', 'estimates', ['created_at'], unique=False)
    op.create_index('ix_estimate_open_status', 'estimates', ['status'], unique=False, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_index('ix_estimate_status', 'estimates', ['status'], unique=False)
    op.create_index('ix_estimate_ticker_id', 'estimates', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_estimates_created_at'), 'estimates', ['created_at'], unique=False)
    op.create_index(op.f('ix_estimates_status'), 'estimates', ['status'], unique=False)
    op.create_index(op.f('ix_estimates_ticker_id'), 'estimates', ['ticker_id'], unique=False)
    op.create_table('market_data',
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.CheckConstraint('close > 0', name='ck_market_data_close_positive'),
    sa.CheckConstraint('high > 0', name='ck_market_data_high_positive'),
    sa.CheckConstraint('high >= close', name='ck_market_data_high_gte_close'),
    sa.CheckConstraint('high >= low', name='ck_market_data_high_gte_low'),
    sa.CheckConstraint('high >= open', name='ck_market_data_high_gte_open'),
    sa.CheckConstraint('low <= close', name='ck_market_data_low_lte_close'),
    sa.CheckConstraint('low <= open', name='ck_market_data_low_lte_open'),
    sa.CheckConstraint('low > 0', name='ck_market_data_low_positive'),
    sa.CheckConstraint('open > 0', name='ck_market_data_open_positive'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0.00 AND quality_score <= 1.00)', name='ck_market_data_quality_score_range'),
    sa.CheckConstraint('volume >= 0', name='ck_market_data_volume_non_negative'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker_id', 'date')
    )
    op.create_index('ix_market_data_date', 'market_data', ['date'], unique=False)
    op.create_index('ix_market_data_ticker_date', 'market_data', ['ticker_id', 'date'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('ai_model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estimate_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_model_runs_model_name_created_at', 'ai_model_runs', ['model_name', 'created_at'], unique=False)
    op.create_table('estimate_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estimate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'UPDATED', 'PRICE_UPDATED', 'TARGET_HIT', 'STOP_HIT', 'CLOSED', 'REOPENED', name='estimate_event_type'), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('timestamp IS NOT NULL', name='ck_estimate_event_timestamp_not_null'),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estimate_event_timeline', 'estimate_events', ['estimate_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_estimate_event_type', 'estimate_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_estimate_events_estimate_id'), 'estimate_events', ['estimate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimate_events_estimate_id'), table_name='estimate_events')
    op.drop_index('ix_estimate_event_type', table_name='estimate_events')
    op.drop_index('ix_estimate_event_timeline', table_name='estimate_events', postgresql_ops={'timestamp': 'DESC'})
    op.drop_table('estimate_events')
    op.drop_index('ix_ai_model_runs_model_name_created_at', table_name='ai_model_runs')
    op.drop_table('ai_model_runs')
    op.drop_table('user_roles')
    op.drop_index('ix_market_data_ticker_date', table_name='market_data')
    op.drop_index('ix_market_data_date', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_estimates_ticker_id'), table_name='estimates')
    op.drop_index(op.f('ix_estimates_status'), table_name='estimates')
    op.drop_index(op.f('ix_estimates_created_at'), table_name='estimates')
    op.drop_index('ix_estimate_ticker_id', table_name='estimates')
    op.drop_index('ix_estimate_status', table_name='estimates')
    op.drop_index('ix_estimate_open_status', table_name='estimates', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_estimate_created_at', table_name='estimates')
    op.drop_table('estimates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_index('ix_ticker_symbol', table_name='tickers')
    op.drop_table('tickers')
    op.drop_index('ix_sync_jobs_started_at', table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_table('roles')
    # ### end Alembic commands ###
